-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity medikinet_cr_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config19_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of medikinet_cr_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config19_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q1 : STD_LOGIC_VECTOR (10 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal a_reg_255 : STD_LOGIC_VECTOR (10 downto 0);
    signal b_reg_260 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln258_fu_142_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln258_1_fu_157_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln267_fu_186_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal exp_table_ce1_local : STD_LOGIC;
    signal exp_table_ce0_local : STD_LOGIC;
    signal invert_table_ce0_local : STD_LOGIC;
    signal icmp_ln66_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_fu_104_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln66_1_fu_108_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln66_fu_112_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_fu_120_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_132_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_2_fu_126_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_147_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_fu_166_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln141_fu_162_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_fu_170_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_fu_176_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln270_fu_198_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln270_fu_191_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_fu_198_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln270_fu_198_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_1_fu_217_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_1_fu_217_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln270_1_fu_217_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal mul_ln270_1_fu_217_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln270_fu_198_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component medikinet_cr_mul_18s_11ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component medikinet_cr_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config19_s_exp_table_ROM_jbC IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component medikinet_cr_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config19_s_invert_table_RkbM IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component medikinet_cr_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config19_s_exp_table_ROM_jbC
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0_local,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1_local,
        q1 => exp_table_q1);

    invert_table_U : component medikinet_cr_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config19_s_invert_table_RkbM
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0_local,
        q0 => invert_table_q0);

    mul_18s_11ns_26_1_1_U23327 : component medikinet_cr_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln270_fu_198_p0,
        din1 => mul_ln270_fu_198_p1,
        dout => mul_ln270_fu_198_p2);

    mul_18s_11ns_26_1_1_U23328 : component medikinet_cr_mul_18s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln270_1_fu_217_p0,
        din1 => mul_ln270_1_fu_217_p1,
        dout => mul_ln270_1_fu_217_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_reg_255 <= exp_table_q1;
                b_reg_260 <= exp_table_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln51_fu_170_p2 <= std_logic_vector(unsigned(zext_ln51_fu_166_p1) + unsigned(zext_ln141_fu_162_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to1)
    begin
        if ((ap_idle_pp0_0to1 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= mul_ln270_fu_198_p2(25 downto 10);
    ap_return_1 <= mul_ln270_1_fu_217_p2(25 downto 10);
    d_xi_xmax_2_fu_126_p2 <= std_logic_vector(unsigned(select_ln66_fu_112_p3) - unsigned(trunc_ln66_1_fu_108_p1));
    d_xi_xmax_fu_120_p2 <= std_logic_vector(unsigned(select_ln66_fu_112_p3) - unsigned(trunc_ln66_fu_104_p1));
    exp_table_address0 <= zext_ln258_1_fu_157_p1(10 - 1 downto 0);
    exp_table_address1 <= zext_ln258_fu_142_p1(10 - 1 downto 0);

    exp_table_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce0_local <= ap_const_logic_1;
        else 
            exp_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce1_local <= ap_const_logic_1;
        else 
            exp_table_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln66_fu_92_p2 <= "1" when (signed(data_0_val) < signed(data_1_val)) else "0";
    invert_table_address0 <= zext_ln267_fu_186_p1(10 - 1 downto 0);

    invert_table_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            invert_table_ce0_local <= ap_const_logic_1;
        else 
            invert_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln270_1_fu_217_p0 <= sext_ln270_fu_191_p1(18 - 1 downto 0);
    mul_ln270_1_fu_217_p1 <= mul_ln270_1_fu_217_p10(11 - 1 downto 0);
    mul_ln270_1_fu_217_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_reg_260),26));
    mul_ln270_fu_198_p0 <= sext_ln270_fu_191_p1(18 - 1 downto 0);
    mul_ln270_fu_198_p1 <= mul_ln270_fu_198_p10(11 - 1 downto 0);
    mul_ln270_fu_198_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_reg_255),26));
    select_ln66_fu_112_p3 <= 
        trunc_ln66_fu_104_p1 when (xor_ln66_fu_98_p2(0) = '1') else 
        trunc_ln66_1_fu_108_p1;
        sext_ln270_fu_191_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(invert_table_q0),26));

    tmp_1_fu_176_p4 <= add_ln51_fu_170_p2(11 downto 8);
    tmp_fu_132_p4 <= d_xi_xmax_fu_120_p2(14 downto 5);
    tmp_s_fu_147_p4 <= d_xi_xmax_2_fu_126_p2(14 downto 5);
    trunc_ln66_1_fu_108_p1 <= data_1_val(15 - 1 downto 0);
    trunc_ln66_fu_104_p1 <= data_0_val(15 - 1 downto 0);
    xor_ln66_fu_98_p2 <= (icmp_ln66_fu_92_p2 xor ap_const_lv1_1);
    zext_ln141_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q1),12));
    zext_ln258_1_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_147_p4),64));
    zext_ln258_fu_142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_132_p4),64));
    zext_ln267_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_176_p4),64));
    zext_ln51_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q0),12));
end behav;
