-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity medikinet_tanh_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_tanh_config3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of medikinet_tanh_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_tanh_config3_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv14_200 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tanh_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table_q1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table_q2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table_q3 : STD_LOGIC_VECTOR (10 downto 0);
    signal index_2_fu_239_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal index_2_reg_651 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal index_5_fu_355_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal index_5_reg_656 : STD_LOGIC_VECTOR (9 downto 0);
    signal index_8_fu_471_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal index_8_reg_661 : STD_LOGIC_VECTOR (9 downto 0);
    signal index_11_fu_587_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal index_11_reg_666 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln465_fu_595_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln465_1_fu_599_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln465_2_fu_603_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln465_3_fu_607_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tanh_table_ce3_local : STD_LOGIC;
    signal tanh_table_ce2_local : STD_LOGIC;
    signal tanh_table_ce1_local : STD_LOGIC;
    signal tanh_table_ce0_local : STD_LOGIC;
    signal trunc_ln458_fu_149_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_153_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_fu_131_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln458_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln458_fu_167_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_141_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln458_fu_173_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_round_fu_181_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln455_fu_189_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal index_fu_193_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_1_fu_203_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln456_fu_199_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal index_1_fu_211_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_4_fu_223_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln463_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln456_1_fu_219_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln458_1_fu_265_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_269_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_9_fu_247_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln458_1_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln458_1_fu_283_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_257_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln458_1_fu_289_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_round_1_fu_297_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln455_1_fu_305_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal index_3_fu_309_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_10_fu_319_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln456_2_fu_315_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal index_4_fu_327_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_12_fu_339_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln463_1_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln456_3_fu_335_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln458_2_fu_381_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_385_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_363_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln458_2_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln458_2_fu_399_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_14_fu_373_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln458_2_fu_405_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_round_2_fu_413_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln455_2_fu_421_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal index_6_fu_425_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_15_fu_435_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln456_4_fu_431_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal index_7_fu_443_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_16_fu_455_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln463_2_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln456_5_fu_451_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln458_3_fu_497_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_501_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_11_fu_479_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln458_3_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln458_3_fu_515_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_17_fu_489_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln458_3_fu_521_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_round_3_fu_529_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln455_3_fu_537_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal index_9_fu_541_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_18_fu_551_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln456_6_fu_547_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal index_10_fu_559_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_19_fu_571_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln463_3_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln456_7_fu_567_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln465_fu_611_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln465_1_fu_615_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln465_2_fu_619_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln465_3_fu_623_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component medikinet_tanh_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_tanh_config3_s_tanh_table_ROM_AUbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    tanh_table_U : component medikinet_tanh_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_tanh_config3_s_tanh_table_ROM_AUbkb
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tanh_table_address0,
        ce0 => tanh_table_ce0_local,
        q0 => tanh_table_q0,
        address1 => tanh_table_address1,
        ce1 => tanh_table_ce1_local,
        q1 => tanh_table_q1,
        address2 => tanh_table_address2,
        ce2 => tanh_table_ce2_local,
        q2 => tanh_table_q2,
        address3 => tanh_table_address3,
        ce3 => tanh_table_ce3_local,
        q3 => tanh_table_q3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                index_11_reg_666 <= index_11_fu_587_p3;
                index_2_reg_651 <= index_2_fu_239_p3;
                index_5_reg_656 <= index_5_fu_355_p3;
                index_8_reg_661 <= index_8_fu_471_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln458_1_fu_283_p2 <= std_logic_vector(unsigned(tmp_9_fu_247_p4) + unsigned(ap_const_lv13_1));
    add_ln458_2_fu_399_p2 <= std_logic_vector(unsigned(tmp_s_fu_363_p4) + unsigned(ap_const_lv13_1));
    add_ln458_3_fu_515_p2 <= std_logic_vector(unsigned(tmp_11_fu_479_p4) + unsigned(ap_const_lv13_1));
    add_ln458_fu_167_p2 <= std_logic_vector(unsigned(tmp_6_fu_131_p4) + unsigned(ap_const_lv13_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to1)
    begin
        if ((ap_idle_pp0_0to1 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= sext_ln465_fu_611_p1;
    ap_return_1 <= sext_ln465_1_fu_615_p1;
    ap_return_2 <= sext_ln465_2_fu_619_p1;
    ap_return_3 <= sext_ln465_3_fu_623_p1;
    data_round_1_fu_297_p3 <= 
        select_ln458_1_fu_289_p3 when (tmp_7_fu_257_p3(0) = '1') else 
        tmp_9_fu_247_p4;
    data_round_2_fu_413_p3 <= 
        select_ln458_2_fu_405_p3 when (tmp_14_fu_373_p3(0) = '1') else 
        tmp_s_fu_363_p4;
    data_round_3_fu_529_p3 <= 
        select_ln458_3_fu_521_p3 when (tmp_17_fu_489_p3(0) = '1') else 
        tmp_11_fu_479_p4;
    data_round_fu_181_p3 <= 
        select_ln458_fu_173_p3 when (tmp_fu_141_p3(0) = '1') else 
        tmp_6_fu_131_p4;
    icmp_ln458_1_fu_277_p2 <= "0" when (tmp_5_fu_269_p3 = ap_const_lv10_0) else "1";
    icmp_ln458_2_fu_393_p2 <= "0" when (tmp_8_fu_385_p3 = ap_const_lv10_0) else "1";
    icmp_ln458_3_fu_509_p2 <= "0" when (tmp_3_fu_501_p3 = ap_const_lv10_0) else "1";
    icmp_ln458_fu_161_p2 <= "0" when (tmp_2_fu_153_p3 = ap_const_lv10_0) else "1";
    icmp_ln463_1_fu_349_p2 <= "0" when (tmp_12_fu_339_p4 = ap_const_lv3_0) else "1";
    icmp_ln463_2_fu_465_p2 <= "0" when (tmp_16_fu_455_p4 = ap_const_lv3_0) else "1";
    icmp_ln463_3_fu_581_p2 <= "0" when (tmp_19_fu_571_p4 = ap_const_lv3_0) else "1";
    icmp_ln463_fu_233_p2 <= "0" when (tmp_4_fu_223_p4 = ap_const_lv3_0) else "1";
    index_10_fu_559_p3 <= 
        ap_const_lv13_0 when (tmp_18_fu_551_p3(0) = '1') else 
        trunc_ln456_6_fu_547_p1;
    index_11_fu_587_p3 <= 
        ap_const_lv10_3FF when (icmp_ln463_3_fu_581_p2(0) = '1') else 
        trunc_ln456_7_fu_567_p1;
    index_1_fu_211_p3 <= 
        ap_const_lv13_0 when (tmp_1_fu_203_p3(0) = '1') else 
        trunc_ln456_fu_199_p1;
    index_2_fu_239_p3 <= 
        ap_const_lv10_3FF when (icmp_ln463_fu_233_p2(0) = '1') else 
        trunc_ln456_1_fu_219_p1;
    index_3_fu_309_p2 <= std_logic_vector(signed(sext_ln455_1_fu_305_p1) + signed(ap_const_lv14_200));
    index_4_fu_327_p3 <= 
        ap_const_lv13_0 when (tmp_10_fu_319_p3(0) = '1') else 
        trunc_ln456_2_fu_315_p1;
    index_5_fu_355_p3 <= 
        ap_const_lv10_3FF when (icmp_ln463_1_fu_349_p2(0) = '1') else 
        trunc_ln456_3_fu_335_p1;
    index_6_fu_425_p2 <= std_logic_vector(signed(sext_ln455_2_fu_421_p1) + signed(ap_const_lv14_200));
    index_7_fu_443_p3 <= 
        ap_const_lv13_0 when (tmp_15_fu_435_p3(0) = '1') else 
        trunc_ln456_4_fu_431_p1;
    index_8_fu_471_p3 <= 
        ap_const_lv10_3FF when (icmp_ln463_2_fu_465_p2(0) = '1') else 
        trunc_ln456_5_fu_451_p1;
    index_9_fu_541_p2 <= std_logic_vector(signed(sext_ln455_3_fu_537_p1) + signed(ap_const_lv14_200));
    index_fu_193_p2 <= std_logic_vector(signed(sext_ln455_fu_189_p1) + signed(ap_const_lv14_200));
    select_ln458_1_fu_289_p3 <= 
        add_ln458_1_fu_283_p2 when (icmp_ln458_1_fu_277_p2(0) = '1') else 
        tmp_9_fu_247_p4;
    select_ln458_2_fu_405_p3 <= 
        add_ln458_2_fu_399_p2 when (icmp_ln458_2_fu_393_p2(0) = '1') else 
        tmp_s_fu_363_p4;
    select_ln458_3_fu_521_p3 <= 
        add_ln458_3_fu_515_p2 when (icmp_ln458_3_fu_509_p2(0) = '1') else 
        tmp_11_fu_479_p4;
    select_ln458_fu_173_p3 <= 
        add_ln458_fu_167_p2 when (icmp_ln458_fu_161_p2(0) = '1') else 
        tmp_6_fu_131_p4;
        sext_ln455_1_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_round_1_fu_297_p3),14));

        sext_ln455_2_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_round_2_fu_413_p3),14));

        sext_ln455_3_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_round_3_fu_529_p3),14));

        sext_ln455_fu_189_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_round_fu_181_p3),14));

        sext_ln465_1_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tanh_table_q2),16));

        sext_ln465_2_fu_619_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tanh_table_q1),16));

        sext_ln465_3_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tanh_table_q0),16));

        sext_ln465_fu_611_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tanh_table_q3),16));

    tanh_table_address0 <= zext_ln465_3_fu_607_p1(10 - 1 downto 0);
    tanh_table_address1 <= zext_ln465_2_fu_603_p1(10 - 1 downto 0);
    tanh_table_address2 <= zext_ln465_1_fu_599_p1(10 - 1 downto 0);
    tanh_table_address3 <= zext_ln465_fu_595_p1(10 - 1 downto 0);

    tanh_table_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tanh_table_ce0_local <= ap_const_logic_1;
        else 
            tanh_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tanh_table_ce1_local <= ap_const_logic_1;
        else 
            tanh_table_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tanh_table_ce2_local <= ap_const_logic_1;
        else 
            tanh_table_ce2_local <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table_ce3_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tanh_table_ce3_local <= ap_const_logic_1;
        else 
            tanh_table_ce3_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_319_p3 <= index_3_fu_309_p2(13 downto 13);
    tmp_11_fu_479_p4 <= data_3_val(15 downto 3);
    tmp_12_fu_339_p4 <= index_4_fu_327_p3(12 downto 10);
    tmp_14_fu_373_p3 <= data_2_val(15 downto 15);
    tmp_15_fu_435_p3 <= index_6_fu_425_p2(13 downto 13);
    tmp_16_fu_455_p4 <= index_7_fu_443_p3(12 downto 10);
    tmp_17_fu_489_p3 <= data_3_val(15 downto 15);
    tmp_18_fu_551_p3 <= index_9_fu_541_p2(13 downto 13);
    tmp_19_fu_571_p4 <= index_10_fu_559_p3(12 downto 10);
    tmp_1_fu_203_p3 <= index_fu_193_p2(13 downto 13);
    tmp_2_fu_153_p3 <= (trunc_ln458_fu_149_p1 & ap_const_lv7_0);
    tmp_3_fu_501_p3 <= (trunc_ln458_3_fu_497_p1 & ap_const_lv7_0);
    tmp_4_fu_223_p4 <= index_1_fu_211_p3(12 downto 10);
    tmp_5_fu_269_p3 <= (trunc_ln458_1_fu_265_p1 & ap_const_lv7_0);
    tmp_6_fu_131_p4 <= data_0_val(15 downto 3);
    tmp_7_fu_257_p3 <= data_1_val(15 downto 15);
    tmp_8_fu_385_p3 <= (trunc_ln458_2_fu_381_p1 & ap_const_lv7_0);
    tmp_9_fu_247_p4 <= data_1_val(15 downto 3);
    tmp_fu_141_p3 <= data_0_val(15 downto 15);
    tmp_s_fu_363_p4 <= data_2_val(15 downto 3);
    trunc_ln456_1_fu_219_p1 <= index_1_fu_211_p3(10 - 1 downto 0);
    trunc_ln456_2_fu_315_p1 <= index_3_fu_309_p2(13 - 1 downto 0);
    trunc_ln456_3_fu_335_p1 <= index_4_fu_327_p3(10 - 1 downto 0);
    trunc_ln456_4_fu_431_p1 <= index_6_fu_425_p2(13 - 1 downto 0);
    trunc_ln456_5_fu_451_p1 <= index_7_fu_443_p3(10 - 1 downto 0);
    trunc_ln456_6_fu_547_p1 <= index_9_fu_541_p2(13 - 1 downto 0);
    trunc_ln456_7_fu_567_p1 <= index_10_fu_559_p3(10 - 1 downto 0);
    trunc_ln456_fu_199_p1 <= index_fu_193_p2(13 - 1 downto 0);
    trunc_ln458_1_fu_265_p1 <= data_1_val(3 - 1 downto 0);
    trunc_ln458_2_fu_381_p1 <= data_2_val(3 - 1 downto 0);
    trunc_ln458_3_fu_497_p1 <= data_3_val(3 - 1 downto 0);
    trunc_ln458_fu_149_p1 <= data_0_val(3 - 1 downto 0);
    zext_ln465_1_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_5_reg_656),64));
    zext_ln465_2_fu_603_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_8_reg_661),64));
    zext_ln465_3_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_11_reg_666),64));
    zext_ln465_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_2_reg_651),64));
end behav;
