-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity medikinet_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of medikinet_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv26_F3A : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000111100111010";
    constant ap_const_lv26_3FFEDC7 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111110110111000111";
    constant ap_const_lv26_3FFECFE : STD_LOGIC_VECTOR (25 downto 0) := "11111111111110110011111110";
    constant ap_const_lv26_1155 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000001000101010101";
    constant ap_const_lv26_11E1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000001000111100001";
    constant ap_const_lv26_DBC : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000110110111100";
    constant ap_const_lv26_3FFF18F : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111000110001111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_5F : STD_LOGIC_VECTOR (15 downto 0) := "0000000001011111";
    constant ap_const_lv16_FFA0 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110100000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal mul_ln42_3_fu_87_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_1_fu_394_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_3_fu_87_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_6_fu_88_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_2_fu_481_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_6_fu_88_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln42_2_fu_89_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_2_fu_89_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln42_1_fu_90_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_fu_368_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_1_fu_90_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln42_4_fu_91_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln42_5_fu_92_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_5_fu_92_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_fu_93_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_fu_93_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_fu_93_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_1_fu_90_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_fu_89_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_3_fu_87_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_fu_420_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_4_fu_91_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln42_fu_435_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_fu_435_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl_fu_439_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_fu_453_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_453_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln42_fu_447_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln42_3_fu_461_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sub_ln42_1_fu_465_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_5_fu_92_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_6_fu_88_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln_fu_374_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_2_fu_400_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_6_fu_487_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_1_fu_513_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_4_fu_425_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_2_fu_519_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_fu_507_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_1_fu_384_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_3_fu_410_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_7_fu_497_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_5_fu_537_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_5_fu_471_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_6_fu_543_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_4_fu_531_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_3_fu_525_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_7_fu_549_p2 : STD_LOGIC_VECTOR (15 downto 0);

    component medikinet_mul_16s_13ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component medikinet_mul_16s_14s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component medikinet_mul_16s_14ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component medikinet_mul_16s_13s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_13ns_26_1_1_U17 : component medikinet_mul_16s_13ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_3_fu_87_p0,
        din1 => mul_ln42_3_fu_87_p1,
        dout => mul_ln42_3_fu_87_p2);

    mul_16s_14s_26_1_1_U18 : component medikinet_mul_16s_14s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_6_fu_88_p0,
        din1 => mul_ln42_6_fu_88_p1,
        dout => mul_ln42_6_fu_88_p2);

    mul_16s_14s_26_1_1_U19 : component medikinet_mul_16s_14s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_2_fu_89_p0,
        din1 => mul_ln42_2_fu_89_p1,
        dout => mul_ln42_2_fu_89_p2);

    mul_16s_14ns_26_1_1_U20 : component medikinet_mul_16s_14ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_1_fu_90_p0,
        din1 => mul_ln42_1_fu_90_p1,
        dout => mul_ln42_1_fu_90_p2);

    mul_16s_14ns_26_1_1_U21 : component medikinet_mul_16s_14ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        dout_WIDTH => 26)
    port map (
        din0 => sext_ln73_fu_420_p0,
        din1 => mul_ln42_4_fu_91_p1,
        dout => mul_ln42_4_fu_91_p2);

    mul_16s_13ns_26_1_1_U22 : component medikinet_mul_16s_13ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_5_fu_92_p0,
        din1 => mul_ln42_5_fu_92_p1,
        dout => mul_ln42_5_fu_92_p2);

    mul_16s_13s_26_1_1_U23 : component medikinet_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_fu_93_p0,
        din1 => mul_ln42_fu_93_p1,
        dout => mul_ln42_fu_93_p2);




    add_ln58_1_fu_513_p2 <= std_logic_vector(unsigned(trunc_ln42_6_fu_487_p4) + unsigned(ap_const_lv16_5F));
    add_ln58_2_fu_519_p2 <= std_logic_vector(unsigned(add_ln58_1_fu_513_p2) + unsigned(trunc_ln42_4_fu_425_p4));
    add_ln58_3_fu_525_p2 <= std_logic_vector(unsigned(add_ln58_2_fu_519_p2) + unsigned(add_ln58_fu_507_p2));
    add_ln58_4_fu_531_p2 <= std_logic_vector(unsigned(trunc_ln42_1_fu_384_p4) + unsigned(trunc_ln42_3_fu_410_p4));
    add_ln58_5_fu_537_p2 <= std_logic_vector(unsigned(trunc_ln42_7_fu_497_p4) + unsigned(ap_const_lv16_FFA0));
    add_ln58_6_fu_543_p2 <= std_logic_vector(unsigned(add_ln58_5_fu_537_p2) + unsigned(trunc_ln42_5_fu_471_p4));
    add_ln58_7_fu_549_p2 <= std_logic_vector(unsigned(add_ln58_6_fu_543_p2) + unsigned(add_ln58_4_fu_531_p2));
    add_ln58_fu_507_p2 <= std_logic_vector(unsigned(trunc_ln_fu_374_p4) + unsigned(trunc_ln42_2_fu_400_p4));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln58_3_fu_525_p2;
    ap_return_1 <= add_ln58_7_fu_549_p2;
    mul_ln42_1_fu_90_p0 <= sext_ln42_fu_368_p1(16 - 1 downto 0);
    mul_ln42_1_fu_90_p1 <= ap_const_lv26_1155(14 - 1 downto 0);
    mul_ln42_2_fu_89_p0 <= sext_ln42_1_fu_394_p1(16 - 1 downto 0);
    mul_ln42_2_fu_89_p1 <= ap_const_lv26_3FFECFE(14 - 1 downto 0);
    mul_ln42_3_fu_87_p0 <= sext_ln42_1_fu_394_p1(16 - 1 downto 0);
    mul_ln42_3_fu_87_p1 <= ap_const_lv26_F3A(13 - 1 downto 0);
    mul_ln42_4_fu_91_p1 <= ap_const_lv26_11E1(14 - 1 downto 0);
    mul_ln42_5_fu_92_p0 <= sext_ln42_2_fu_481_p1(16 - 1 downto 0);
    mul_ln42_5_fu_92_p1 <= ap_const_lv26_DBC(13 - 1 downto 0);
    mul_ln42_6_fu_88_p0 <= sext_ln42_2_fu_481_p1(16 - 1 downto 0);
    mul_ln42_6_fu_88_p1 <= ap_const_lv26_3FFEDC7(14 - 1 downto 0);
    mul_ln42_fu_93_p0 <= sext_ln42_fu_368_p1(16 - 1 downto 0);
    mul_ln42_fu_93_p1 <= ap_const_lv26_3FFF18F(13 - 1 downto 0);
    p_shl_fu_439_p3 <= (trunc_ln42_fu_435_p1 & ap_const_lv12_0);
        sext_ln42_1_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_val),26));

        sext_ln42_2_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_3_val),26));

        sext_ln42_3_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_453_p3),26));

        sext_ln42_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_0_val),26));

    sext_ln73_fu_420_p0 <= data_2_val;
    sub_ln42_1_fu_465_p2 <= std_logic_vector(unsigned(sub_ln42_fu_447_p2) - unsigned(sext_ln42_3_fu_461_p1));
    sub_ln42_fu_447_p2 <= std_logic_vector(unsigned(ap_const_lv26_0) - unsigned(p_shl_fu_439_p3));
    tmp_fu_453_p1 <= data_2_val;
    tmp_fu_453_p3 <= (tmp_fu_453_p1 & ap_const_lv2_0);
    trunc_ln42_1_fu_384_p4 <= mul_ln42_1_fu_90_p2(25 downto 10);
    trunc_ln42_2_fu_400_p4 <= mul_ln42_2_fu_89_p2(25 downto 10);
    trunc_ln42_3_fu_410_p4 <= mul_ln42_3_fu_87_p2(25 downto 10);
    trunc_ln42_4_fu_425_p4 <= mul_ln42_4_fu_91_p2(25 downto 10);
    trunc_ln42_5_fu_471_p4 <= sub_ln42_1_fu_465_p2(25 downto 10);
    trunc_ln42_6_fu_487_p4 <= mul_ln42_5_fu_92_p2(25 downto 10);
    trunc_ln42_7_fu_497_p4 <= mul_ln42_6_fu_88_p2(25 downto 10);
    trunc_ln42_fu_435_p0 <= data_2_val;
    trunc_ln42_fu_435_p1 <= trunc_ln42_fu_435_p0(14 - 1 downto 0);
    trunc_ln_fu_374_p4 <= mul_ln42_fu_93_p2(25 downto 10);
end behav;
