-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity medikinet_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of medikinet_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv26_BDA : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000101111011010";
    constant ap_const_lv26_3FFF431 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111010000110001";
    constant ap_const_lv26_3FFF4F6 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111010011110110";
    constant ap_const_lv26_3FFF487 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111010010000111";
    constant ap_const_lv26_9EB : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000100111101011";
    constant ap_const_lv26_3FFF43D : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111010000111101";
    constant ap_const_lv26_3FFF5B0 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111010110110000";
    constant ap_const_lv26_3FFF4F8 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111010011111000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv64_10 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010000";
    constant ap_const_lv16_F964 : STD_LOGIC_VECTOR (15 downto 0) := "1111100101100100";
    constant ap_const_lv16_65D : STD_LOGIC_VECTOR (15 downto 0) := "0000011001011101";
    constant ap_const_lv16_600 : STD_LOGIC_VECTOR (15 downto 0) := "0000011000000000";
    constant ap_const_lv16_F969 : STD_LOGIC_VECTOR (15 downto 0) := "1111100101101001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal mul_ln42_9_fu_62_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_fu_387_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_9_fu_62_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_13_fu_63_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_1_fu_443_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_13_fu_63_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_11_fu_64_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_11_fu_64_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_12_fu_65_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_12_fu_65_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_7_fu_66_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_7_fu_66_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_10_fu_67_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_10_fu_67_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_8_fu_68_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_8_fu_68_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_fu_69_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_fu_69_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal a_fu_383_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_fu_69_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_7_fu_66_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_8_fu_68_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_9_fu_62_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal a_1_fu_435_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_10_fu_67_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_11_fu_64_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_12_fu_65_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_13_fu_63_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln42_1_fu_451_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_fu_491_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_395_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_2_fu_461_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_9_fu_503_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_8_fu_405_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_3_fu_471_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_11_fu_515_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_9_fu_415_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_4_fu_481_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_13_fu_527_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_s_fu_425_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_8_fu_497_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_10_fu_509_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_12_fu_521_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_14_fu_533_p2 : STD_LOGIC_VECTOR (15 downto 0);

    component medikinet_mul_16s_13ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component medikinet_mul_16s_13s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_13ns_26_1_1_U1 : component medikinet_mul_16s_13ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_9_fu_62_p0,
        din1 => mul_ln42_9_fu_62_p1,
        dout => mul_ln42_9_fu_62_p2);

    mul_16s_13s_26_1_1_U2 : component medikinet_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_13_fu_63_p0,
        din1 => mul_ln42_13_fu_63_p1,
        dout => mul_ln42_13_fu_63_p2);

    mul_16s_13s_26_1_1_U3 : component medikinet_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_11_fu_64_p0,
        din1 => mul_ln42_11_fu_64_p1,
        dout => mul_ln42_11_fu_64_p2);

    mul_16s_13s_26_1_1_U4 : component medikinet_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_12_fu_65_p0,
        din1 => mul_ln42_12_fu_65_p1,
        dout => mul_ln42_12_fu_65_p2);

    mul_16s_13ns_26_1_1_U5 : component medikinet_mul_16s_13ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_7_fu_66_p0,
        din1 => mul_ln42_7_fu_66_p1,
        dout => mul_ln42_7_fu_66_p2);

    mul_16s_13s_26_1_1_U6 : component medikinet_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_10_fu_67_p0,
        din1 => mul_ln42_10_fu_67_p1,
        dout => mul_ln42_10_fu_67_p2);

    mul_16s_13s_26_1_1_U7 : component medikinet_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_8_fu_68_p0,
        din1 => mul_ln42_8_fu_68_p1,
        dout => mul_ln42_8_fu_68_p2);

    mul_16s_13s_26_1_1_U8 : component medikinet_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_fu_69_p0,
        din1 => mul_ln42_fu_69_p1,
        dout => mul_ln42_fu_69_p2);




    a_1_fu_435_p3 <= data_val(31 downto 16);
    a_fu_383_p1 <= data_val(16 - 1 downto 0);
    add_ln58_10_fu_509_p2 <= std_logic_vector(unsigned(add_ln58_9_fu_503_p2) + unsigned(trunc_ln42_8_fu_405_p4));
    add_ln58_11_fu_515_p2 <= std_logic_vector(unsigned(trunc_ln42_3_fu_471_p4) + unsigned(ap_const_lv16_600));
    add_ln58_12_fu_521_p2 <= std_logic_vector(unsigned(add_ln58_11_fu_515_p2) + unsigned(trunc_ln42_9_fu_415_p4));
    add_ln58_13_fu_527_p2 <= std_logic_vector(unsigned(trunc_ln42_4_fu_481_p4) + unsigned(ap_const_lv16_F969));
    add_ln58_14_fu_533_p2 <= std_logic_vector(unsigned(add_ln58_13_fu_527_p2) + unsigned(trunc_ln42_s_fu_425_p4));
    add_ln58_8_fu_497_p2 <= std_logic_vector(unsigned(add_ln58_fu_491_p2) + unsigned(trunc_ln_fu_395_p4));
    add_ln58_9_fu_503_p2 <= std_logic_vector(unsigned(trunc_ln42_2_fu_461_p4) + unsigned(ap_const_lv16_65D));
    add_ln58_fu_491_p2 <= std_logic_vector(unsigned(trunc_ln42_1_fu_451_p4) + unsigned(ap_const_lv16_F964));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln58_8_fu_497_p2;
    ap_return_1 <= add_ln58_10_fu_509_p2;
    ap_return_2 <= add_ln58_12_fu_521_p2;
    ap_return_3 <= add_ln58_14_fu_533_p2;
    mul_ln42_10_fu_67_p0 <= sext_ln73_1_fu_443_p1(16 - 1 downto 0);
    mul_ln42_10_fu_67_p1 <= ap_const_lv26_3FFF43D(13 - 1 downto 0);
    mul_ln42_11_fu_64_p0 <= sext_ln73_1_fu_443_p1(16 - 1 downto 0);
    mul_ln42_11_fu_64_p1 <= ap_const_lv26_3FFF4F6(13 - 1 downto 0);
    mul_ln42_12_fu_65_p0 <= sext_ln73_1_fu_443_p1(16 - 1 downto 0);
    mul_ln42_12_fu_65_p1 <= ap_const_lv26_3FFF487(13 - 1 downto 0);
    mul_ln42_13_fu_63_p0 <= sext_ln73_1_fu_443_p1(16 - 1 downto 0);
    mul_ln42_13_fu_63_p1 <= ap_const_lv26_3FFF431(13 - 1 downto 0);
    mul_ln42_7_fu_66_p0 <= sext_ln73_fu_387_p1(16 - 1 downto 0);
    mul_ln42_7_fu_66_p1 <= ap_const_lv26_9EB(13 - 1 downto 0);
    mul_ln42_8_fu_68_p0 <= sext_ln73_fu_387_p1(16 - 1 downto 0);
    mul_ln42_8_fu_68_p1 <= ap_const_lv26_3FFF5B0(13 - 1 downto 0);
    mul_ln42_9_fu_62_p0 <= sext_ln73_fu_387_p1(16 - 1 downto 0);
    mul_ln42_9_fu_62_p1 <= ap_const_lv26_BDA(13 - 1 downto 0);
    mul_ln42_fu_69_p0 <= sext_ln73_fu_387_p1(16 - 1 downto 0);
    mul_ln42_fu_69_p1 <= ap_const_lv26_3FFF4F8(13 - 1 downto 0);
        sext_ln73_1_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_1_fu_435_p3),26));

        sext_ln73_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_fu_383_p1),26));

    trunc_ln42_1_fu_451_p4 <= mul_ln42_10_fu_67_p2(25 downto 10);
    trunc_ln42_2_fu_461_p4 <= mul_ln42_11_fu_64_p2(25 downto 10);
    trunc_ln42_3_fu_471_p4 <= mul_ln42_12_fu_65_p2(25 downto 10);
    trunc_ln42_4_fu_481_p4 <= mul_ln42_13_fu_63_p2(25 downto 10);
    trunc_ln42_8_fu_405_p4 <= mul_ln42_7_fu_66_p2(25 downto 10);
    trunc_ln42_9_fu_415_p4 <= mul_ln42_8_fu_68_p2(25 downto 10);
    trunc_ln42_s_fu_425_p4 <= mul_ln42_9_fu_62_p2(25 downto 10);
    trunc_ln_fu_395_p4 <= mul_ln42_fu_69_p2(25 downto 10);
end behav;
